### ISSUE TITLE
Need last commited Sequence

### ISSUE THREAD

**Issue by alifpay** [nats-io/stan.go#248]
Hi 
Trying NATS streaming server. We want to use for communication between services. 
sometimes client restarts, so need to get message from last subscribed.
Is there a solution how to get messages from last committed sequence in QueueSubscribe?  pick up where it left

Is it good idea to save last sequence that received message?

After the nats streaming server is restarted, go-nats-streaming is not get messages. how to resolve this issue?

**Comment by kozlovic** [comment]
For the client side, if you want the client to resume work from where it left before being stopped, simply use a durable subscription. Check [this](https://github.com/nats-io/go-nats-streaming#subscription-start-ie-replay-options) whole section (including durables and queue (durable) groups).

For the server restart, if you use a persistent store, clients should receive messages after the server restart. Note that by default the server uses a memory store, where no state can be recovered. Provide `-store file -dir <datastore directory>` to have persistence (https://github.com/nats-io/nats-streaming-server#persistence). I would recommend reading the entire README, it is not that long.

**Comment by alifpay** [comment]
thank you very much.
`sc, err := stan.Connect(clusterID, clientID, stan.NatsURL(URL),
		stan.SetConnectionLostHandler(func(_ stan.Conn, reason error) {
			log.Printf("Connection lost, reason: %v", reason)
		}))
	if err != nil {
		log.Fatalf("Can't connect: %v.\nMake sure a NATS Streaming Server is running at: %s", err, URL)
	}`

How to reconnect lost connection?

**Comment by kozlovic** [comment]
@alifpay  Sorry for the delay.

First, I should point out that the default pings from client to server are pretty aggressive. That is, a ping every 5 seconds, and fail the connection after the 4th attempt. So if you want to be able to have your application survive a longer time between a server restart for instance, then you can increase those values (with the `stan.Pings()` option setter that you pass to `Connect()`) but then not too high otherwise you take the risk of having your application not know that the connection is no longer valid for a while (check [this](https://github.com/nats-io/go-nats-streaming#connection-status)).

To reconnect the connection, you can use the handler to restart all the connection logic and recreate your subscriptions if applicable.
You could have something like this:
```
func connect(params you need) stan.Conn {
    sc, err := stan.Connect(.., 
     stan.SetConnectionLostHandler(func(_ stan.Conn, reason error) {
         newsc := connect(..)
         // If applicable create subs
         createSubs(newSc, ..)
    }))
    if err := nil {
    ...
    }
    return sc
}

func createSubs(sc stan.Conn, ..) {
} 
```
