### ISSUE TITLE
"publish ack timeout" received frequently on stan-bench test

### ISSUE THREAD

**Issue by mmanna-sapfgl** [nats-io/stan.go#257]
Before I created this issue, I researched on github to check for any duplicates.

https://github.com/nats-io/nats-streaming-server/issues/520

#520 isn't relevant, but I see a comment form @kozlovic that the timeout is expected. If the publisher goes offline before the server's ack is received, then this message will be shown. I am assuming that stan-bench test spawns different threads which are terminated before the acks can be received?

Attached is my config file. 
[streamer_conf.txt](https://github.com/nats-io/stan.go/files/3171893/streamer_conf.txt)

Here is the command i used for stan-bench

`stan-bench.exe -c streamer1 -s nats://localhost:4223 -id foofighter1 -ms 4000000 -ns 100 -np 100 -n 100 foo`

**Comment by kozlovic** [comment]
@mmanna-sapfgl Make sure you are running from master since I have fixed some issues post 0.14.1

The problem I see is that you are running 100 subscriptions that each need to receive a 4,000,000 bytes message for every single published message. That is more than 380MB outbound per inbound message. 

(btw, you are running with debug/trace which is very verbose, I would recommend turning that off when running benchmarks).

Note that anytime you restart the start bench program as shown above with an existing state, it means that the server will deliver all messages to these 100 subscriptions, which means reading from the head of the log (disk read) while adding new messages to end of the log. If you want to ignore old messages and start the bench subscriptions "fresh", you should pass `-io` for ignore old messages.

**Comment by mmanna-sapfgl** [comment]
> 
> 
> @mmanna-sapfgl Make sure you are running from master since I have fixed some issues post 0.14.1
> 
> The problem I see is that you are running 100 subscriptions that each need to receive a 4,000,000 bytes message for every single published message. That is more than 380MB outbound per inbound message.
> 
> (btw, you are running with debug/trace which is very verbose, I would recommend turning that off when running benchmarks).
> 
> Note that anytime you restart the start bench program as shown above with an existing state, it means that the server will deliver all messages to these 100 subscriptions, which means reading from the head of the log (disk read) while adding new messages to end of the log. If you want to ignore old messages and start the bench subscriptions "fresh", you should pass `-io` for ignore old messages.

Very helpful response! Thanks a lot for that. Espcially, this 380MB restriction on ingress. I have now disabled trace/debug all together.

Is this 380MB restriction mentioned in Readme? Because I looked in to stan.go/nats-streaming-server readme and it doesn't metnion this.

**Comment by mmanna-sapfgl** [comment]
Just to add to my previous comments, I have trimmed things down a lot and running with the following

`.\stan-bench.exe -c streamer1 -id foofighter1 -qgroup foofighter.group1 -ms 3000000 -ns 10 -np 10 -n 10 -s nats://192.168.99.100:4223 -io foo`

My intention is to stress this out at log scale (e.g. 10 > 100 > 1000 pub sub) - with a max payload size and see where the issue is happening. with 10 subscriptions for 10 messages - I am aiming for 400 MB ingress/egress. From what you are saying above, I can only reach 380 MB. 

Since my original config has almost no limites set on max messages and bytes, I am not sure which parameters are needed to be tweaked. If this is an internal restriction, I guess I simply need to know where this is.  

Also, it seems that `-ns` `-np` and `-n` are not strictly maintained, but it's actually the average. For example, the stan command I put above yields the following (with Runtime index OOR error too).

`Starting benchmark [msgs=10, msgsize=3000000, pubs=10, subs=10]
NATS Streaming Pub/Sub stats: 32 msgs/sec ~ 94.35 MB/sec
 Pub stats: 11 msgs/sec ~ 33.85 MB/sec
  [1] 5 msgs/sec ~ 15.11 MB/sec (1 msgs)
  [2] 1 msgs/sec ~ 3.71 MB/sec (1 msgs)
  [3] 1 msgs/sec ~ 3.71 MB/sec (1 msgs)
  [4] 1 msgs/sec ~ 3.73 MB/sec (1 msgs)
  [5] 1 msgs/sec ~ 3.73 MB/sec (1 msgs)
  [6] 1 msgs/sec ~ 3.71 MB/sec (1 msgs)
  [7] 1 msgs/sec ~ 3.39 MB/sec (1 msgs)
  [8] 1 msgs/sec ~ 3.40 MB/sec (1 msgs)
  [9] 1 msgs/sec ~ 3.40 MB/sec (1 msgs)
  [10] 1 msgs/sec ~ 3.41 MB/sec (1 msgs)
  min 1 | avg 1 | max 5 | stddev 1 msgs
 Sub stats: 28 msgs/sec ~ 80.25 MB/sec
  [1] %!v(PANIC=String method: runtime error: index out of range) (1 msgs)
  [2] 3 msgs/sec ~ 8.62 MB/sec (2 msgs)
  [3] 4 msgs/sec ~ 11.54 MB/sec (2 msgs)
  [4] 4 msgs/sec ~ 13.12 MB/sec (2 msgs)
  [5] 5 msgs/sec ~ 15.03 MB/sec (2 msgs)
  [6] 6 msgs/sec ~ 17.77 MB/sec (2 msgs)
  [7] 7 msgs/sec ~ 21.63 MB/sec (2 msgs)
  [8] 9 msgs/sec ~ 27.65 MB/sec (2 msgs)
  [9] 13 msgs/sec ~ 38.57 MB/sec (2 msgs)
  [10] 22 msgs/sec ~ 64.43 MB/sec (2 msgs)
  min -9,223,372,036,854,775,808 | avg 922,337,203,685,477,588 | max 22 | stddev 3,325,534,081,156,063,232 msgs`

By the look of it, a queue group member seems to be dropping 1 msg all the time. I ran this 10 times, and every time I am seeing this on the logs. I also tried to delete all existing files and restarted the docker container, and tried the above again. I still see this index error for 1 subscriber. Does this mean the message is lost, or some other error. 

One last thing, I believe it would help in the future to list all the configuration properties for server, publisher, and subscriber to be "Tabular". In this way, we can always refer that section when asking such questions. Wanted to point this out since you mentioned we're going through a refresh process.

Thanks,

**Comment by kozlovic** [comment]
@mmanna-sapfgl I have never said that there was a limit of 380MB, I simply stated that you have to be mindful of what load you are generating in your tests. Always keep in mind: for a given inbound message, the number of outbound that the server will have to send is: number of subs * message size.

When you send a 3 or 4MB message, and you plan to have 1000 subscribers, you are looking at 4GB of data per message, or 32 Giga bits.. not sure the system (as a whole, software and hardware) will be able to handle that.

On your initial report, I believe that you may be hitting one of the issue I have fixed in master and so I would strongly recommend that you run your tests with server built from master.

Notes about the bench *example* program: it uses a connection per publisher and a connection per subscriber. So before you run with high cardinality of pub and sub, keep in mind the number of file descriptors that you will need, especially if both bench and server run on the same machine.

Lastly, you now start to use queue subscriptions. You should know that for a given message, only a member of the same queue group will receive that message. That is, if a message is sent and there is 10 queue subscribers of the same group, only one queue member gets it. So you can't run from the same bench program `-np` and `-ns` with queue group since by definition not all members will get all messages.

**Comment by mmanna-sapfgl** [comment]
> 
> 
> @mmanna-sapfgl I have never said that there was a limit of 380MB, I simply stated that you have to be mindful of what load you are generating in your tests. Always keep in mind: for a given inbound message, the number of outbound that the server will have to send is: number of subs * message size.
> 
> When you send a 3 or 4MB message, and you plan to have 1000 subscribers, you are looking at 4GB of data per message, or 32 Giga bits.. not sure the system (as a whole, software and hardware) will be able to handle that.
> 
> On your initial report, I believe that you may be hitting one of the issue I have fixed in master and so I would strongly recommend that you run your tests with server built from master.
> 
> Notes about the bench _example_ program: it uses a connection per publisher and a connection per subscriber. So before you run with high cardinality of pub and sub, keep in mind the number of file descriptors that you will need, especially if both bench and server run on the same machine.
> 
> Lastly, you now start to use queue subscriptions. You should know that for a given message, only a member of the same queue group will receive that message. That is, if a message is sent and there is 10 queue subscribers of the same group, only one queue member gets it. So you can't run from the same bench program `-np` and `-ns` with queue group since by definition not all members will get all messages.

Thanks for the explanation. Do you know when the new image will be pushed to dockerhub?

**Comment by kozlovic** [comment]
Not sure exactly. Working on some clustering issues at the moment. Maybe end of this week or next.

**Comment by kozlovic** [comment]
Closing for now.. Will re-open if new information is available.

**Comment by hsahuntnx** [comment]
@kozlovic I am consistently experiencing this issue in a smaller setup as well.

**Starting benchmark [msgs=1000000, msgsize=100, pubs=10, subs=20]
Publisher "benchmark-pub-8" got following error: stan: publish ack timeout**

whereas I am not facing this issue with a large setup.
**Starting benchmark [msgs=1000000, msgsize=1000, pubs=10, subs=25]
NATS Streaming Pub/Sub stats: 86,640 msgs/sec ~ 82.63 MB/sec**

Both the benchmarking tests are identical (freshly deployed cluster)

here is my server configuration
`
port: 4222
cluster: {
	"listen": "0.0.0.0:6222",
}

streaming: {
	"sd": true,
	"id": "nats-streaming-cluster-poc",
	"store": "File",
	"dir": "/data/nats_data_dir/filestore",
	"cluster": {
		"log_path": "/data/nats_data_dir/cluster_log_path",
		"node_id": "node_id",
		"bootstrap": true
	},
	"tls": {
		"client_ca": "/config/certs/ca.pem"
	},
	"file_options": {
		"buffer_size": 64000000,
		"read_buffer_size": 64000000,
		"parallel_recovery": 2,
		"slice_max_msgs": 10000000,
		"slice_max_bytes": 500000000
	},
	"store_limits": {
		"max_bytes": 1000000000,
		"max_msgs": 10000000,
		"max_subs": 1000,
		"max_age": "1h",
		"max_inactivity": "1h",
		"max_channels": 5000
	}
}

tls: {
	"cert_file": "/config/certs/server.crt",
	"key_file": "/config/certs/server_key.pem",
	"ca_file": "/config/certs/ca.pem",
	"insecure": false
}
`

**Comment by kozlovic** [comment]
@hsahuntnx That is weird. Are you restarting the cluster from fresh between each run? Just so you know, if you run the bench tool it will be default try to get all messages, so if you repeat runs with the same channel names, new messages will be appended, but server will have to go back at beginning of channel to deliver old messages. There is a `-io` (for ignore old messages) option. That still does not explain why you would not be having issues with larger messages, unless you start test with larger messages, then smaller for the same channel?

**Comment by hsahuntnx** [comment]
@kozlovic no, I am deleting existing cluster, deleting data directory and recreating new cluster with same configuration between each run. **Every iteration is running on a freshly deployed cluster.** 
Also _If I reduce the number of messages to publish_ or _increase the message size_, I don't see this issue that often. This issue is very frequent in smaller message sizes (100 bytes, 256 bytes).
Also, my server is running over TLS.
