### ISSUE TITLE
Request using https inside a handler not working on Linux and macOS

### ISSUE THREAD

**Issue by pedrobisp** [nats-io/stan.go#283]
When doing a request inside a subscriber handler, if this request uses https, it will end up hanging.
This issue only occurs on Linux and macOS, on Windows it works properly.

A toy repo with an example is available here: https://github.com/pedrobisp/nats-io-stango-repo

**Comment by kozlovic** [comment]
You are doing an infinite loop with the `for {}` which consumes all CPU and seems to prevent the TLS setup to be done properly (in the net package, nothing to do with NATS). I have done 2 things that make the "issue" disappear:
1- The wrong one: do an https request before reaching the `for {}` loop at the end of the program, and you will see that the https get does not fail anymore.
2- The right thing: replace `for {}` with either proper signal handling - so that you can close the connection (check our examples programs in `examples/` directory for some help) - or at least this:
```
(..)
	_, err = sc.Subscribe("backend", getRequest, stan.StartAtTime(time.Now()))
	if err != nil {
		log.Fatalf("Error subscribing to chanel:%v", err)
	}
        ch := make(chan struct{})
        <-ch
}
```
