### ISSUE TITLE
Provide a way to set GUID on Publish to avoid publishing duplicates

### ISSUE THREAD

**Issue by powerman** [nats-io/stan.go#293]
Application which must guarantee message related to some change in app DB will be published on a channel is supposed to store an "outgoing message queue" in same DB (and make that changes in app DB together with appending message to that "outgoing message queue" in same DB transaction). Next app will publish these messages and remove them from "outgoing message queue" on ACK. Then on restart after crash application have to process all elements in that "outgoing message queue" and re-publish them all.

There is a possibility some of them was already published (and even ACKed) before crash, but wasn't removed from "outgoing message queue" because of crash. This means such messages may be duplicated in STAN channel on app restart.

As Publish already internally uses GUID to avoid duplicates in STAN channel on re-publishing messages after PubAckWait, it would be nice to reuse this feature to also avoid mentioned above duplicates after application restart.

At a glance it looks like it's enough to let application generate GUIDs on it's own, store GUID together with message subject and data in "outgoing message queue", and provide that GUID as an argument to the Publish call.

To make this work STAN server must be able to correctly detect duplicates by GUID even if they was received after long enough delay (like days) and even if STAN server itself was restarted within that period of time. (Probably this may be limited to last MaxPubAcksInflight messages, not sure.) But I suppose this is already implemented, isn't it?

So, how about extending stan.Conn interface with a couple more methods?
```go
PublishOnce(guid, subject string, data []byte) error
PublishOnceAsync(guid, subject string, data []byte, ah AckHandler) (string, error)
```

**Comment by kozlovic** [comment]
> As Publish already internally uses GUID to avoid duplicates in STAN channel on re-publishing messages after PubAckWait

This is a wrong assumption: the GUID is simply used to match a published message with the pubAck that client may receive from the server. There is no duplicate detection in the server, and the library never re-publish a message if it got a timeout on PubAckWait.

The GUID is not stored anywhere in the streaming server. Changing that (to use as a duplicate detection) would cause a backward compatibility break (file/DB format would have to change to include the GUID) and we are not going to do that since JetStream is now where new development goes. Fixes and "small" new features (unlikely to break backward compatibility) will be done for NATS Streaming, but major changes like this one is unlikely.
