### ISSUE TITLE
how to request messages with sequence number

### ISSUE THREAD

**Issue by matti** [nats-io/stan.go#311]
When I connect to a streaming server and send messages I see the sequence numbers - but how do I request all messages that I might have missed? (eg: https://docs.nats.io/nats-concepts/seq_num) 

It looks like this client doesn't support that?

**Comment by kozlovic** [comment]
@matti, not sure if you wanted to ask about NATS core or NATS Streaming.
My answer for NATS core would be:

NATS core does not have persistence and sequence numbers. It is at-most-once delivery.
What the doc refer to is that application can add logic in their message encoding so that they can detect gaps if desired. But that is not done in the server or the libraries.

For NATS Streaming, the server will redeliver messages if the application does not acknowledge them. You can detect if you want that your application missed messages by checking the msg.Sequence, but you don't have to.

**Comment by matti** [comment]
thanks, I think the readme could be improved to point newbies like me to stan from nats :)
