### ISSUE TITLE
High Memory Usage.

### ISSUE THREAD

**Issue by meetme2meat** [nats-io/stan.go#314]
We are facing an issue wherein our pods are getting evicted because of High Memory usages. I have been chasing this issue using the `top` and `pprof` tools and preliminary inspection states that most of the memory is held by NATS client (i.e internal of nats).

```
(pprof) top20
Showing nodes accounting for 1152.06MB, 99.78% of 1154.56MB total
Dropped 3 nodes (cum <= 5.77MB)
      flat  flat%   sum%        cum   cum%
 1139.04MB 98.66% 98.66%  1139.04MB 98.66%  github.com/nats-io/nats%2ego.(*Conn).processMsg
   13.02MB  1.13% 99.78%    15.52MB  1.34%  main.parse
         0     0% 99.78%  1139.04MB 98.66%  github.com/nats-io/nats%2ego.(*Conn).parse
         0     0% 99.78%  1139.04MB 98.66%  github.com/nats-io/nats%2ego.(*Conn).readLoop
         0     0% 99.78%    15.52MB  1.34%  github.com/nats-io/nats%2ego.(*Conn).waitForMsgs
         0     0% 99.78%    15.52MB  1.34%  github.com/nats-io/stan%2ego.(*conn).processMsg
         0     0% 99.78%    15.52MB  1.34%  main.processMsg
```

```
(pprof) lines
(pprof) top20
Showing nodes accounting for 1152.06MB, 99.78% of 1154.56MB total
Dropped 6 nodes (cum <= 5.77MB)
      flat  flat%   sum%        cum   cum%
  966.53MB 83.71% 83.71%   966.53MB 83.71%  github.com/nats-io/nats%2ego.(*Conn).processMsg /Users/admin/Documents/goProject/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2264
  127.51MB 11.04% 94.76%   127.51MB 11.04%  github.com/nats-io/nats%2ego.(*Conn).processMsg /Users/admin/Documents/goProject/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2268
      45MB  3.90% 98.66%       45MB  3.90%  github.com/nats-io/nats%2ego.(*Conn).processMsg /Users/admin/Documents/goProject/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2257
   13.02MB  1.13% 99.78%    13.02MB  1.13%  main.parse /Users/admin/Documents/goProject/leak-golang-nats/leak_nats.go:217
         0     0% 99.78%       12MB  1.04%  github.com/nats-io/nats%2ego.(*Conn).parse /Users/admin/Documents/goProject/pkg/mod/github.com/nats-io/nats.go@v1.10.0/parser.go:154
         0     0% 99.78%  1127.04MB 97.62%  github.com/nats-io/nats%2ego.(*Conn).parse /Users/admin/Documents/goProject/pkg/mod/github.com/nats-io/nats.go@v1.10.0/parser.go:177
         0     0% 99.78%  1139.04MB 98.66%  github.com/nats-io/nats%2ego.(*Conn).readLoop /Users/admin/Documents/goProject/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2147
         0     0% 99.78%    15.52MB  1.34%  github.com/nats-io/nats%2ego.(*Conn).waitForMsgs /Users/admin/Documents/goProject/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2211
         0     0% 99.78%    15.52MB  1.34%  github.com/nats-io/stan%2ego.(*conn).processMsg /Users/admin/Documents/goProject/pkg/mod/github.com/nats-io/stan.go@v0.6.0/stan.go:863
         0     0% 99.78%    15.52MB  1.34%  main.processMsg /Users/admin/Documents/goProject/leak-golang-nats/leak_nats.go:170
```
The `top` utility yield following result

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
105032 deploy    20   0 2616576   2.4g   5120 S 100.0 17.8   1221:04 leak-nats
```

I have condensed down the application into a bare minimum along with the push client, pprof file, and the actual sample CSV file into the following zip file(i.e [sample.zip](https://github.com/nats-io/stan.go/files/4796550/sample.zip)). The script has been running in one of **my tests server from the past 16 hours** and all of the above results are in fact from the past 16 hours processing.

If it helps we are using the `FILE` store for our nats-streaming client. Also, I noticed the files listed above (in pprof) are internal to NATS and not NATS-streaming but since we are using NATS-streaming client I decided to address this issue over here.

**Comment by kozlovic** [comment]
Let me explain how NATS Streaming (re)delivery works, what that meant to your test and how to make it behave better.

### How it works
When the NATS Streaming server delivers messages to a subscription, it sends up to the subscription's MaxInflight option (assuming that many messages are available). These messages are received through the low-level NATS Subscription, unmarshal as a pb.MsgProto, then after some checks to see if subscription is still active, it invokes the user streaming on message callback (from the NATS on message callback). After processing, when the user callback returns, the message acknowledgment is sent (unless user defines a manual ack mode, in which case the user is responsible for acknowledging the message).
If the server does not receive an acknowledgment from the subscription within the subscription's option AckWait, it will redeliver the message. That can happen many times if the application still does not acknowledge the message.
Take a simple but extreme example: the subscription has AckWait of 1 second and receives a message but takes 30 seconds to process that message. The server will have redelivered this message 30 times... which means that this message will be in the NATS subscription's pending list 30 times. After the user's streaming on message callback returns, the next message is dispatched, which happens to be the same, and if the application does not detect it as a duplicate and ignores, then the message may take as much time. The server will stop redelivering the message because it received the ACK, but that does nothing to those 30 redelivered messages that are waiting to be dispatched.
Why is the library not detecting those as duplicates? Because it would mean keeping a map of sequences that have been seen (for how long?). For non queue subs, we could keep a floor that would allow reducing the size of that map, but for queue subs, we can't because a queue member could receive redelivered messages from other members that leave the group with seq number well below what this member has seen.

### How does it affect your test
You are using default MaxInflight (1024) and AckWait (30s) when you create your queue subscription. What is immediately clear is that your subscription's callback is not only "slow" compared to the rate of publishing, but simply slow, that is, can consume only few messages a second (on my machine, about 7 messages a second).
Due to the imbalance (or by modifying your sub to start at beginning of channel and with channel pre-filed), some delivered messages will stay in the client queue for longer than the AckWait, which will cause the server to redeliver those (see explanation of what that leads to above).
I ran your test and made it much worse by just reducing the AckWait to 1 second (down from default of 30 seconds) so I could see the memory usage grow quickly.
The pprof shows that the number of objects in use are payload/messages/subjects from nats.go, which coincide with the number of pending messages in the low level NATS Subscription. I added that after creating the sub:

**Comment by kozlovic** [comment]
@meetme2meat I assume that you tried the suggestion and it solved the memory usage that you observed. I am closing this for now and will re-open if needed.

**Comment by dswarbrick** [comment]
I'd just like to say that this was very helpful in my use case also. We are sending protobufs over streaming NATS, and each of those protobuf messages contains up to 8192 repeated elements. This means that our rate of processing NATS messages is (relatively) slow, and the default `MaxInflight` was resulting in huge amounts of memory on the heap in the nats.go `processMsg` function.

Reducing `MaxInflight` _significantly_ reduced heap usage, whilst still being able to process the same number of repeated elements per second from our protobuf. In other words, our app is currently still CPU-bound, and needs further parallelism - but at least we now have the memory usage under control!

Thank you very much for the hint!

**Comment by kozlovic** [comment]
@dswarbrick Glad this helped!

**Comment by gharia** [comment]
Hi Team,

We are facing same memory issue with NATS core. We are not using JetStream. 

```
hemraj@192 ~ % go tool pprof -inuse_space http://localhost:9000/debug/pprof/heap
Fetching profile over HTTP from http://localhost:9000/debug/pprof/heap
Saved profile in /Users/hemraj/pprof/pprof.quote-socket.alloc_objects.alloc_space.inuse_objects.inuse_space.015.pb.gz
File: quote-socket
Type: inuse_space
Time: Oct 17, 2024 at 7:55pm (IST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 14338.93MB, 99.07% of 14473.90MB total
Dropped 155 nodes (cum <= 72.37MB)
Showing top 10 nodes out of 16
      flat  flat%   sum%        cum   cum%
 6927.28MB 47.86% 47.86% 12933.31MB 89.36%  github.com/nats-io/nats%2ego.(*Conn).parse
 6006.03MB 41.50% 89.36%  6006.03MB 41.50%  github.com/nats-io/nats%2ego.(*Conn).processMsg
  798.15MB  5.51% 94.87%   798.15MB  5.51%  google.golang.org/protobuf/internal/impl.mergeInt32Slice
  606.42MB  4.19% 99.06%   675.92MB  4.67%  gitlab.quotes.io/quotes/reference-service/reference.(*Client).fetchAllInstruments
    0.56MB 0.0038% 99.06%   799.20MB  5.52%  gitlab.quotes.io/quotes/bzgo/internal/quote-socket/manager.(*QuoteManager).updateCache
    0.50MB 0.0035% 99.07%   798.65MB  5.52%  google.golang.org/protobuf/internal/impl.(*MessageInfo).mergePointer
         0     0% 99.07%   675.92MB  4.67%  github.com/cenkalti/backoff.RetryNotify
         0     0% 99.07%   798.65MB  5.52%  github.com/golang/protobuf/proto.Merge
         0     0% 99.07% 12933.31MB 89.36%  github.com/nats-io/nats%2ego.(*Conn).readLoop
         0     0% 99.07%   802.78MB  5.55%  gitlab.quotes.io/quotes/bzgo/internal/quote-socket/manager.(*QuoteManager).Run
```

Any insights what could be wrong? FYI, we are trying to use NATS for realtime stock quotes streaming.

Thanks

**Comment by kozlovic** [comment]
@gharia I would do a `list processMsg` and see where this memory is being used. My guess is that it is from messages that have been enqueued to one or more subscriptions that are not being consumed at all or fast enough. How many subscriptions do you have? Are they sync or async? Do you consume fast enough? Do you get any slow consumer errors from the application (you should register an error callback at the connection level)?

If the above points do not lead you right a way to a resolution, please open a new issue in the [NATS Go Client](https://github.com/nats-io/nats.go) repository instead of adding to this issue from the NATS Streaming Go client that has been EOL for a while now. Thanks!
