### ISSUE TITLE
Trying to receive last message of particular Channel (Message Size : 50 KB) ,Using API using JMeter ,1000 threads per minute ,getting Error :  stan: subscribe request timeoutError .How to solve it ?

### ISSUE THREAD

**Issue by LokkaPatel** [nats-io/stan.go#321]
This issue is coming in multithreading.
Related Issue :
[https://github.com/nats-io/stan.net/issues/108]

**Comment by LokkaPatel** [comment]
Same cluster ID is used .

**Comment by kozlovic** [comment]
I would ask that you describe a bit better your problem. Maybe provide some example code that reproduce the issue. That being said, if you try to create thousands of subscriptions per second, it could be that the server is not able to handle that and the requests are timing out. You could increase the default timeout (this is the ConnectWait() option but this timeout is used for all internal requests such as creating the subscription). But I would first like to understand what the actual problem is instead of changing this value.

**Comment by LokkaPatel** [comment]
var j uint64 = 0
	clean := make(chan bool)
	sc1,err1 := scHeartBeat.Subscribe("Channel100", func(m *stan.Msg) {
			j = m.Sequence
			if j >= 0 {
				clean <- true
			}
			fmt.Fprintf(w,"Last message no: %d\n", m.Sequence)
		},stan.StartWithLastReceived())
		<-clean
		if err1 != nil {
			clean <- true
			fmt.Printf("HeartBeat : Error in Receiving Last Message for Channel100 for Client \n")
			fmt.Fprintf(w,"Error in Receiving Last Message for Channel100 for Client \n")
			fmt.Printf("%v\n", err1)
		}
		//<-clean
		sc1.Unsubscribe()

**Comment by LokkaPatel** [comment]
For Server I used Comamnd Line Argument "-**sc config.file -file_auto_sync=1ms --file_sync=false**".

Config.file  Input  ->

cluster_id: test-cluster
max_payload: 10485760
streaming {
  hb_fail_count: 360
  store: FILE
  dir: "D:\\go\\server\\DataStore"
  store_limits {
    max_subs: 0
	max_channels: 0
    max_msgs: 0
    max_bytes: 0
  }
}

**Comment by LokkaPatel** [comment]
func HeartBeat(w http.ResponseWriter, r *http.Request){
	iHeartBeatCnt++
	fmt.Fprintf(w, "HeartBeat : Page hit %d\n",iHeartBeatCnt)
	//fmt.Println("HeartBeat : page hit",iHeartBeatCnt)
	
	if errHeartBeat != nil {
		fmt.Fprintf(w, "Not able to Connect Client \n")
		fmt.Printf("Not able to Connect Client \n")
		fmt.Println(errHeartBeat)
		return
	}
	
	subj := "lastConn"

	msg := []byte("HeatBeat11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111")
	// Simple Synchronous Publisher
	err2 := scHeartBeat.Publish(subj,msg)
	if err2 != nil {
		fmt.Printf("HeartBeat : Error in Publishing for Client \n")
		fmt.Fprintf(w,"Error in Publishing for Client \n")
		fmt.Println(err2)
		//sc.Close()
		return
	}	
	//fmt.Printf("Published [%s] : %s\n", subj, msg)
	//fmt.Fprintf(w,"Published [%s] : %s\n", subj, msg)

	var j uint64 = 0
	clean := make(chan bool)
	fmt.Printf("HeartBeat : Clean is Created")
	sc1,err1 := scHeartBeat.Subscribe("Channel100", func(m *stan.Msg) {
			j = m.Sequence
			if j >= 0 {
				clean <- true
			}
			fmt.Fprintf(w,"Last message no: %d\n", m.Sequence)
		},stan.StartWithLastReceived())
		<-clean
		if err1 != nil {
			//clean <- true
			fmt.Printf("HeartBeat : Error in Receiving Last Message for Channel100 for Client \n")
			fmt.Fprintf(w,"Error in Receiving Last Message for Channel100 for Client \n")
			fmt.Printf("%v\n", err1)			
		}
		//<-clean
		sc1.Unsubscribe()
		fmt.Printf("HeartBeat : Clean is closed")
		//close(clean)
	
	if iHeartBeatCnt == 1 && j > 0{
		cleanupDone := make(chan bool)
		sub, err := scHeartBeat.Subscribe("Channel100", func(m *stan.Msg) {
			uHeartBeatDurable++
			if m.Sequence >= j {
				//fmt.Fprintf(w,"[%d] : Received a message: %s\n", uHeartBeatDurable, string(m.Data))
				cleanupDone <- true
			}
			fmt.Fprintf(w,"[%d] : Received a message: %s\n", uHeartBeatDurable, string(m.Data))
		},stan.DeliverAllAvailable())
		<-cleanupDone
		if err != nil {
			fmt.Println(err)
			return
		}
		close(cleanupDone)
		//fmt.Printf("Listening on [%s], clientID=[%s]\n", subj, clientID)
		sub.Unsubscribe()
	}else if j > uHeartBeatDurable {
		cleanup := make(chan bool)
		var x uint64 = uHeartBeatDurable + 1
		sub, err := scHeartBeat.Subscribe("Channel100", func(m *stan.Msg) {
			uHeartBeatDurable++
			if m.Sequence >= j {
				//fmt.Fprintf(w,"[%d] : Received a message: %s\n", uHeartBeatDurable, string(m.Data))
				cleanup <- true
			}
			fmt.Fprintf(w,"[%d] : Received a message: %s\n", uHeartBeatDurable, string(m.Data))
		},stan.StartAtSequence(x))
		<-cleanup
		if err != nil {
			fmt.Println(err)
			return
		}
		close(cleanup)
		sub.Unsubscribe()
	}

}

**Comment by LokkaPatel** [comment]
I used this function for HeartBeat API .

**Comment by LokkaPatel** [comment]
**I faced issues in subscribing messages of large size like 50 KB. Not able to receive it without Creating Channel.**

**Comment by kozlovic** [comment]
I am sorry but you will have to explain a bit better, not simply showing code, of what your issue is and what you are really trying to do.
But looking at the above code I see plenty of issues (but again, I don't understand what you are trying to do, so it is a bit difficult to comment).

First I see that you have variables such as iHeartBeatCnt and uHeartBeatDurable that gets set/incremented without any locking. HeartBeat() seem to be an http handler and that can be invoked from multiple go routines, so this is really wrong.

Second, this code:
```
sc1,err1 := scHeartBeat.Subscribe("Channel100", func(m *stan.Msg) {
   j = m.Sequence
   if j >= 0 {
      clean <- true
   }
   fmt.Fprintf(w,"Last message no: %d\n", m.Sequence)
},stan.StartWithLastReceived())
<-clean
if err1 != nil {
   //clean <- true
   fmt.Printf("HeartBeat : Error in Receiving Last Message for Channel100 for Client \n")
   fmt.Fprintf(w,"Error in Receiving Last Message for Channel100 for Client \n")
   fmt.Printf("%v\n", err1)			
}
//<-clean
sc1.Unsubscribe()
```
The sequence will always be 1 or above, so you can remove `if j >= 0`. But you need to limit the number of messages this subscription can handle and should use manual ack mode so that server does not send more than one (otherwise the callback will be left hanging trying to send to the `clean` go channel.
Waiting on `<-clean` before checking for the error is wrong. If you were really unable to create the subscription you would not know because you are blocked waiting on `<-clean`.
You should also unsubscribe directly from the callbac. So a better code would be:
```
	var j uint64
	last := make(chan uint64)
	if _, err := sc.Subscribe("Channel100", func(m *stan.Msg) {
		last <- m.Sequence
		m.Sub.Unsubscribe()
	}, stan.StartWithLastReceived(), stan.SetManualAckMode(), stan.MaxInflight(1)); err != nil {
		fmt.Printf("HeartBeat : Error in Receiving Last Message for Channel100 for Client \n")
		fmt.Fprintf(w, "Error in Receiving Last Message for Channel100 for Client \n")
		fmt.Printf("%v\n", err)
	}
	select {
	case j = <-last:
	case <-time.After(1 * time.Second):
		// Channel did not have any message, handle this situation
	}
```
But then after that, not sure what you are trying to do. But "j" will change if you get concurrent invocations of HeartBeat() so you should probably protect the whole function with a lock. 
I am sorry I can't be of more help if I don't understand what you are trying to do and what is the actual issue you are observing.

**Comment by LokkaPatel** [comment]
Hi @kozlovic ,
Thanks for your help ,but after certain amount of time (around 4 minutes) after running the test in JMeter ,getting error : **HeartBeat : Error in Receiving Last Message for Channel100 for Client** . Stan Error  **stan: subscribe request timeout** , Is it because of large message size ?

**Comment by LokkaPatel** [comment]
In the above the HeartBeat Function ,I am trying to get offset messages ,when I hit the API ? 

- Firstly I am trying to get sequence of last message in j.

- I am keeping track of messages received with uHeartBeatDurable , it's like counter.

- Then, if it's first hit of API ,I am trying to receive all delivered messages , by comparing with j.

-Then ,if it's not first API, I am tring to receive messages from sequence  uHeartBeatDurable .

**Comment by LokkaPatel** [comment]
I checked by increasing  stan.MaxInflight() and by increasing time in case for channel ,but it's not working

**Comment by kozlovic** [comment]
But you don't address this remark: an http handler will be invoked concurrently if there is multiple hit to the endpoint. So is there a case where HeartBeat() will be invoked concurrently? If so, all global variables are not thread safe and bad things will happen.

From the description of what you are doing with `j` and `uHeartBeatDurable` it almost look to me like you are simply trying to implement what a durable subscription is. If you use `stan.DurableName()` as an option to the `Subscribe()` call, the server is maintaining which messages have been sent/ack'ed by this durable subscription. You can resume a durable at any time: once created, the start position is ignored since the server maintains the position. That is, say when you first create a durable you want to receive all messages in the channel you would use the `stan.DeliverAllAvailable()` option. But if later the durable subscription is closed and later you want to resume it, you don't have to worry about passing `stan.DeliverAllAvailable()`, the server is not going to resend everything from the beginning: only the messages that were not acknowledged and the new ones. See https://docs.nats.io/nats-streaming-concepts/channels/subscriptions/durable and https://docs.nats.io/developing-with-nats-streaming/durables.

> after running the test in JMeter ,getting error : HeartBeat : Error in Receiving Last Message for Channel100 for Client . Stan Error stan: subscribe request timeout .And I checked, there are messages in the Channel100 . Is it because of large message size ?

Again, that's the point: you are simulating load on HeartBeat() API which means that there will be concurrent calls to this function, which the code as you showed me is wrong for concurrent access.
You may be creating lots of subscriptions and add lot of load on the server, which will be unable to process your subscription request in time.

**Comment by LokkaPatel** [comment]
I tried with stan.DurableName() function but it was not working that's why I came with this Idea .

**Comment by LokkaPatel** [comment]
And I created another functions publishing the messages through API ,they are working fine but getting issue with subscribing only.

**Comment by kozlovic** [comment]
> I tried with stan.DurableName() function but it was not working that's why I came with this Idea . It's not able to receive messages.

Not working how? Durables are formed using clientID+channel+durable name, which means that there can be a single instance running. Based on my understanding of what you are doing obviously this won't work because you may invoke HeartBeat() concurrently, which again I think is wrong.
You could use durable queue groups instead, but not understanding what you are trying to do, I don't feel comfortable recommending anything.

If you would like to do a Google Hangout to discuss in more details your issue, I am willing to do that because at this point I think we have a communication issue that prevents me from helping you.

**Comment by LokkaPatel** [comment]
I tried stan-durable for single instance also but it's not working.Sure ,we can discuss the issue on Google Hangouts . Thanks @kozlovic

**Comment by kozlovic** [comment]
@LokkaPatel Please send me an email to ivan@synadia.com with your availability, and I will send you an invite. Note that I am based in the US Mountain Time.

**Comment by LokkaPatel** [comment]
sure , thanks @kozlovic. I am closing this issue.

**Comment by kozlovic** [comment]
@LokkaPatel If you do wish to pursue and are sending me an email, please make sure to update this issue here with a simple comment saying that you did send an email. This will allow me to acknowledged that I have received it, because it could be that it goes to spam or blocked, etc.. Thanks!
