### ISSUE TITLE
Support get last message

### ISSUE THREAD

**Issue by quintans** [nats-io/stan.go#324]
I have a a service A that is polling data from system X. Service A then publishes the polled data into a NATS topic.
When service A crashes, it needs to start polling the data, from the last successfully published data to the NATS topic.
I could keep track of the last successfully published data in a database, but in the event of a crash there is a possibility of a inconsistency between the saved data and the published data, leading to repeated data being published, something that I want to avoid.
To avoid this inconsistency, it would be useful if service A could get the last message in the topic, read the data, and start polling from there.
Is there a way to read the last publish data into a topic?

**Comment by alifpay** [comment]
I find this in in readme.md Subscription Start (i.e. Replay) Options
but nothing about last delivered message.

```
// Subscribe starting with most recently published value
sub, err := sc.Subscribe("foo", func(m *stan.Msg) {
    fmt.Printf("Received a message: %s\n", string(m.Data))
}, stan.StartWithLastReceived())

stan.StartAtSequence(22)

```

Is this to get last message in the topic, if put durable stan.DurableName("service-a") ?

or we have to save last Sequence in db of service A?

**Comment by alifpay** [comment]
I did like this

```go


//Client of nats streaming server
type Client struct {
	nc   *nats.Conn
	lock sync.RWMutex
	sc   stan.Conn
	core *app.Core
}

//Connect to nats streaming server
func Connect(urls string, tlsCfg *tls.Config, ac *app.Core) (c *Client, err error) {

	// Setup the connect options
	opts := []nats.Option{nats.Name("providers")}
	// Use UserCredentials
	//if *userCreds != "" {
	//opts = append(opts, nats.UserCredentials(*userCreds))
	//}
	if strings.Contains(urls, "tls://") {
		opts = append(opts, nats.Secure(tlsCfg))
	}
	opts = append(opts, nats.ReconnectWait(5*time.Second))
	opts = append(opts, nats.MaxReconnects(-1))
	opts = append(opts, nats.DisconnectErrHandler(func(nc *nats.Conn, err error) {
		log.Printf("Disconnected due to:%s, will attempt reconnects for 5sec", err)
	}))
	opts = append(opts, nats.ReconnectHandler(func(nc *nats.Conn) {
		log.Printf("Reconnected [%s]", nc.ConnectedUrl())
	}))
	opts = append(opts, nats.ClosedHandler(func(nc *nats.Conn) {
		log.Printf("Exiting: %v", nc.LastError())
	}))

	c.nc, err = nats.Connect(urls, opts...)
	if err != nil {
		return
	}

	c.core = ac
	return
}

//Close -
func (c *Client) Close() {
	if c.nc != nil {
		c.sc.Close()
		c.nc.Drain()
		c.nc.Close()
	}
}

//ConnectStream -
func (c *Client) ConnectStream(ctx context.Context, clusterID, clientID, subject, durableName string) (err error) {
	c.lock.Lock()
	c.sc, err = stan.Connect(clusterID, clientID, stan.NatsConn(c.nc),
		stan.SetConnectionLostHandler(func(_ stan.Conn, reason error) {
			log.Printf("Connection lost, reason: %v", reason)
			time.Sleep(15 * time.Second)
			c.ConnectStream(ctx, clusterID, clientID, subject, durableName)
		}))
	c.lock.Unlock()
	if err != nil {
		return err
	}

	msgHandler := func(m *stan.Msg) {
		c.payments(m.Data)
	}
	// Subscribe with durable name
	c.sc.Subscribe(subject, msgHandler, stan.DurableName(durableName))
	<-ctx.Done()
	return nil
}


```

**Comment by ripienaar** [comment]
StartWithLastReceived() with will give the last, this is where it starts the first time it sees a particular client, next time, when you do not unsubscribe, Streaming Server will remember you and give you since where you were before.  No need to store the ID unless you specifically want to go to a specific ID

> 
> or we have to save last Sequence in db of service A?

**Comment by kozlovic** [comment]
@quintans 

> I have a a service A that is polling data from system X. Service A then publishes the polled data into a NATS topic.
When service A crashes, it needs to start polling the data, from the last successfully published data to the NATS topic.

You don't really say where is NATS Streaming in the picture, so it is a bit difficult to answer correctly. But if I assume that the polling from system X uses NATS Streaming, you could imagine service A using a durable subscription and use manual ack mode. When getting a message it would then publish and only if publish succeeds, then ack the message.

This means that if service A crashes, it will get the last unacknowledged message (the one(s) it failed to ack), so you can publish again. Of course, there is always a possibility that the publish was successful but the service crashed before sending the ACK. As always, NATS Streaming offers at-least-once delivery semantic, so that something your application would have to handle.

> I could keep track of the last successfully published data in a database, but in the event of a crash there is a possibility of a inconsistency between the saved data and the published data, leading to repeated data being published, something that I want to avoid. To avoid this inconsistency, it would be useful if service A could get the last message in the topic, read the data, and start polling from there. Is there a way to read the last publish data into a topic?

So now you are talking about getting the last message on the channel service A is publishing to, right? If that is the case, and as long as you can correlate the message sequence from the message on the destination channel with the one in the source channel (in system X), then yes, you could create a subscription with the `stan.StartWithLastReceived()` as part of the subscription option. In this case, do NOT create a durable subscription since for durables, the start position is used only the first time the durable is started, not after that.

**Comment by quintans** [comment]
@kozlovic sorry for the late reply but I am not getting notifications
To answer your question service A only publishes and another service B is the one using nats streaming, as you correctly understood by your third paragraph.
To full flow would be `system X (external) <- service A -> NATS -> service B (nats streaming)`
It seems I misunderstood the docs. I did a small test and in fact it is as you say.
Thank you all for your replies.
