### ISSUE TITLE
Proposal: Add UserInfo opt

### ISSUE THREAD

**Issue by Russiancold** [nats-io/stan.go#354]
Is it possible to add any options for providing user credentials directly, not by `nats.Conn`?

**Comment by kozlovic** [comment]
Instead of adding individual NATS options, I think it would make more sense to have ability to add NATS options (or array of function Option) so that when stan library creates the NATS connection, it can uses those options (if provided) to setup the NATS connection. Keep in mind that the library would still overwrite some of the options like it does today.
Does that sound ok to you?

(PS: for basic user/password connection, you can always pass it to the URL: `nats://user:pwd@host:port`)

**Comment by kozlovic** [comment]
@Russiancold Please have a look at PR #355.

**Comment by Russiancold** [comment]
Looks good! Thanks!
